type: app
description: Default stackfile usecase description
# template used to create the project
template: csv-list-column/<template-name>
inputs:
  some_input: value
# list of plugins to be applied after project creation
plugins:
  - plugin: csv-list-column/<plugin-name>
    inputs:
      some_input: value
      some_list:
        - item1
        - item2
